"""
PDF export: renders the structured report JSON into styled HTML (its own template, not reused from render_markdown_report()) and feeds that into WeasyPrint to produce a real PDF file.
"""

import datetime as _dt
import html as _html
import json, os, re
from typing import Dict, Optional

from ..common import now_iso
from ..config import PDFS_DIR, RUNS_DIR

PDF_CSS = """
@page {
    size: A4;
    margin: 2.2cm 2cm;
    @bottom-center {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 9px;
        color: #888;
    }
}
body {
    font-family: 'Helvetica Neue', Arial, sans-serif;
    color: #1a1a1a;
    line-height: 1.55;
    font-size: 11pt;
}
.report-title {
    font-size: 24pt;
    font-weight: 700;
    color: #14213d;
    margin-bottom: 0.1cm;
}
.report-meta {
    font-size: 9pt;
    color: #888;
    margin-bottom: 1cm;
    border-bottom: 2px solid #14213d;
    padding-bottom: 0.4cm;
}
h2 {
    font-size: 15pt;
    color: #14213d;
    border-left: 4px solid #fca311;
    padding-left: 0.3cm;
    margin-top: 1cm;
    margin-bottom: 0.35cm;
    page-break-after: avoid;
}
h2.exec-summary-heading {
    border-left-color: #14213d;
}
p {
    margin: 0 0 0.35cm 0;
    text-align: justify;
    orphans: 3;
    widows: 3;
}
.exec-summary {
    background: #f5f6f8;
    border-radius: 6px;
    padding: 0.5cm 0.6cm;
    font-style: italic;
    color: #333;
}
.section-tag {
    display: inline-block;
    font-size: 8pt;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: #fca311;
    font-weight: 700;
    margin-bottom: 0.15cm;
}
ul.checklist {
    list-style: none;
    padding-left: 0;
    margin-top: 0.2cm;
}
ul.checklist li {
    position: relative;
    padding: 0.18cm 0 0.18cm 0.9cm;
    border-bottom: 1px solid #eee;
    page-break-inside: avoid;
}
ul.checklist li::before {
    content: "";
    position: absolute;
    left: 0;
    top: 0.28cm;
    width: 0.4cm;
    height: 0.4cm;
    border: 1.5px solid #14213d;
    border-radius: 3px;
}
.footer-note {
    margin-top: 1.2cm;
    font-size: 8pt;
    color: #aaa;
    border-top: 1px solid #eee;
    padding-top: 0.3cm;
}
"""

def _html_escape(text: str) -> str:
    return _html.escape(str(text or ""))

def _paragraphs_html(text: str) -> str:
    """Turn a plain-text/loosely-formatted section body into <p> blocks —
    specialist/synthesizer output is prose with blank-line breaks, not
    Markdown, so this just escapes and wraps rather than running a full
    Markdown renderer."""
    text = str(text or "").strip()
    if not text:
        return "<p><em>No content.</em></p>"
    blocks = re.split(r"\n\s*\n", text)
    return "\n".join(f"<p>{_html_escape(block).replace(chr(10), '<br/>')}</p>" for block in blocks if block.strip())

def render_report_html(report: Dict, run_id: str = "", generated_at: Optional[str] = None) -> str:
    """Render the structured report JSON (same shape as `final_report_json`) into a standalone, styled HTML document ready for WeasyPrint."""
    generated_at = generated_at or now_iso()
    title = report.get("title", "Business Plan Report")

    display_time = generated_at
    try:
        parsed = _dt.datetime.fromisoformat(generated_at.replace("Z", "+00:00"))
        display_time = parsed.strftime("%Y-%m-%d %H:%M UTC")
    except (ValueError, AttributeError):
        pass
    
    meta_bits = [f"Generated {display_time}"]
    if run_id:
        meta_bits.append(f"Run ID: {run_id}")
    meta_line = " &middot; ".join(_html_escape(b) for b in meta_bits)

    body_parts = [f'<div class="report-title">{_html_escape(title)}</div>', f'<div class="report-meta">{meta_line}</div>']
 
    summary = report.get("executive_summary")
    if summary:
        body_parts.append('<h2 class="exec-summary-heading">Executive Summary</h2>')
        body_parts.append(f'<div class="exec-summary">{_paragraphs_html(summary)}</div>')
 
    for section in report.get("sections", []):
        heading = section.get("heading") or section.get("specialist", "Section").replace("_", " ").title()
        specialist = section.get("specialist")
        body_parts.append("<div>")
        if specialist:
            body_parts.append(f'<div class="section-tag">{_html_escape(specialist.replace("_", " "))}</div>')
        body_parts.append(f"<h2>{_html_escape(heading)}</h2>")
        body_parts.append(_paragraphs_html(section.get("content", "")))
        body_parts.append("</div>")
 
    checklist = report.get("checklist", [])
    if checklist:
        body_parts.append("<h2>Checklist &amp; Next Steps</h2>")
        items = "\n".join(f"<li>{_html_escape(item)}</li>" for item in checklist)
        body_parts.append(f'<ul class="checklist">{items}</ul>')
 
    body_parts.append(
        '<div class="footer-note">Generated by an autonomous multi-agent business-planning '
        "system (LangGraph orchestrator, Groq/Gemini specialist &amp; verifier agents). "
        "AI-generated content — verify figures and claims before acting on them.</div>"
    )
 
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{_html_escape(title)}</title>
<style>{PDF_CSS}</style>
</head>
<body>
{''.join(body_parts)}
</body>
</html>"""

def export_report_pdf(report: Dict, run_id: str, generated_at:  Optional[str] = None) -> Optional[str]:
    """Render `report` to PDF and save it to pdfs/report_<run_id>.pdf."""
    try:
        from weasyprint import HTML
    except ImportError:
        print("[PDF] weasyprint is not installed - skipping PDF export.")
        return None
    
    html_str = render_report_html(report, run_id=run_id, generated_at=generated_at)

    os.makedirs(PDFS_DIR, exist_ok=True)
    output_path = os.path.join(PDFS_DIR, f"report_{run_id}.pdf")

    try:
        HTML(string=html_str).write_pdf(output_path)
    except Exception as e:
        print(f"[PDF] PDF export failed ({type(e).__name__}: {e}).")
        return None
    
    print(f"[PDF] Report exported to: {output_path}")
    return output_path

def regenerate_pdf_from_saved_run(run_id: str) -> Optional[str]:
    """Rebuild a PDF from a previously saved runs/run_<id>.json record, without re-running the (rate-limited, API-cost-incurring) full pipeline."""
    path = os.path.join(RUNS_DIR, f"run_{run_id}.json")
    if not os.path.exists(path):
        print(f"[PDF] No saved run record found at {path}")
        return None
    with open(path, "r", encoding="utf-8") as f:
        record = json.load(f)
    return export_report_pdf(record.get("final_report", {}), run_id)